spring.application.name=products
spring.datasource.url=jdbc:mariadb://localhost:3308/boutique
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/KeycloakSpring
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/KeycloakSpring/protocol/openid-connect/certs



keycloak.realm=KeycloakSpring
keycloak.auth-server-url=http://localhost:8080
keycloak.resource=products
keycloak.credentials.secret=admin
keycloak.public-client=false
keycloak.ssl-required=external


server.port=8980
